import { Injectable, Logger } from '@nestjs/common';
import { HttpService } from '@nestjs/axios';
import { ConfigService } from '@nestjs/config';
import { firstValueFrom } from 'rxjs';

@Injectable()
export class ExternalApiService {
  private readonly logger = new Logger(ExternalApiService.name);
  private readonly baseUrl: string;
  private readonly endpointPattern: string;

  constructor(
    private readonly httpService: HttpService,
    private readonly configService: ConfigService,
  ) {
    this.baseUrl = this.configService
      .get<string>('externalApi.baseUrl', 'http://localhost:5010')
      .replace(/\/+$/, '');
    this.endpointPattern = this.configService.get<string>(
      'externalApi.quotationUpdateEndpoint',
      '/api/Quotations/:id/pdf-url',
    );
  }

  /**
   * Updates the quotation with the generated PDF URL in the external Main API.
   *
   * @param quotationId - The ID of the quotation (data.id)
   * @param pdfUrl - The public PDF URL generated by the storage service
   */
  async updateQuotationPdfUrl(quotationId: string, pdfUrl: string): Promise<void> {
    const formattedEndpoint = this.endpointPattern.replace(':id', quotationId);
    const targetUrl = `${this.baseUrl}${
      formattedEndpoint.startsWith('/') ? formattedEndpoint : `/${formattedEndpoint}`
    }`;

    const payload = { quotationPdfUrl: pdfUrl };

    this.logger.log(
      `Sending PUT request to External API: ${targetUrl} with quotationPdfUrl: ${pdfUrl}`,
    );

    try {
      const response = await firstValueFrom(
        this.httpService.put(targetUrl, payload, {
          headers: {
            accept: '*/*',
            'Content-Type': 'application/json',
          },
        }),
      );

      this.logger.log(
        `Successfully updated quotation ${quotationId} on External API. Status: ${response.status}`,
      );
    } catch (error) {
      this.logger.error(
        `Failed to update quotation ${quotationId} on External API at ${targetUrl}: ${error?.message}`,
        error?.response?.data || error?.stack,
      );
      throw error;
    }
  }
}
